steps:
  - label:  ":hammer: Test Woodhouse"
    command: './.buildkite/steps/test.sh'
    agents:
      queue: docker
    timeout_in_minutes: 5
    retry:
      automatic:
      # In the event of a -1 exit code (a build-timeout or agent lost), retry up to 2 times
      # Work-around for weird npm network hangs we've seen
      - exit_status: -1
        limit: 2

  - wait

  - label:  ":thinking_face: Check if branch should be deployed"
    command: './.buildkite/steps/should-deploy.sh'
    agents:
      queue: docker
    timeout_in_minutes: 5
